#!/usr/bin/env bash

# Script to run test/*sql files. Pass error lines to stderr, and exit
# with a non-zero value in that case.

me=$(basename $0)

if [ $# -lt 1 ]; then
    echo "usage: $me TEST.sql [...]" 1>&2
    exit 1
fi

errors=0
for test in "$@"; do
    good=0
    fail=0
    warn=0
    total=0
    while read -r line; do
        ((total++))
        if [ "$VERBOSE" == 1 ]; then
            echo $line
        fi
        case "$line" in
            NULL)
                ;;
            [0-9]_[0-9][0-9]*1)
                ((good++))
                ;;
            [0-9]_[0-9][0-9]*)
                ((fail++))
                ;;
            [0-9][0-9]*1)
                ((good++))
                ;;
            [0-9][0-9]*)
                ((fail++))
                ;;
            *)
                ((warn++))
                if [ "$VERBOSE" != 1 ]; then
                    echo $line
                fi
                ;;
        esac
    done < <(
    HOME=. sqlite3 2>&1 <<-EOF
		.headers off
		.mode tabs
		.read $test
		.quit
EOF
    )

    ((errors += $?))
    ((errors += $fail))
    ((errors += $warn))

    if [ $fail -gt 0 -o $warn -gt 0 ]; then
        printf "%s: fail: %d, warn: %d, ok: %d, total: %d\n" \
            $test $fail $warn $good $total 1>&2
    else
        echo $test: ok: $good
    fi
done

if [ $errors -gt 0 ]; then
    exit 1
fi
