name: build

on:
    push:
        branches: [main]
        paths:
            - .github/**
            - src/**
            - test/**
            - Makefile
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Default build
              shell: bash
              run: |
                  ./configure
                  make test
