name: Build

on:
    push:
        branches: [build]
    workflow_dispatch:

jobs:
    Linux:
        name: build-linux
        uses: ./.github/workflows/build-linux.yml
    MacOS:
        name: build-macos
        uses: ./.github/workflows/build-macos.yml
    Windows:
        name: build-windows
        uses: ./.github/workflows/build-windows.yml
